### PR TITLE
updates header.scss to ass box-shadow effects

### PR DESCRIPTION
**Pull request by rhtaylor**
---
name: Shadow effect on PopUp component
about: enables users to see the form better. 
title: Box Shadow for PopUp component

---
issue 126: Adds a box shadow to PopUp Component so it delineates form and webpage. 

scss update
adds scss box-shadow to .overlay
popup
noshadow

- [x] Local Tests are passing.
- [ ] New tests have been added for new code where relevant
- [x] Screenshots of before and after changes have been added
- [x] JSDoc Documentation and comments have been added or updated in the code.
- [x] Documentation in the /docs folder has been added or updated when appropirate.
- [x] Follows Nouri JavaScript guidelines
- [x] Commit message follows Nouri guidelines
- [x] Introduces minimal or no additional external packages.

Example:

Closes <issue 126>

### CODE REVIEW

**Comment by RaevLogic** [comment]
Why did the close out "x" get moved to the center? Just curious.

**Comment by rhtaylor** [comment]
The X centering looks nicer in my opinion. I usually try to center things as much as I can.

**Comment by ambergkim** [comment]
🤔 I think the x in the center draws attention to it.

With forms you want the eyes to be drawn first to the heading and then directed towards the submit button.

We want to "discourage" people from exiting out.

**Comment by ambergkim** [comment]
Putting the x away from the way our eyes flows draws less attention to it.

**Comment by rhtaylor** [comment]
noshadow
Done

**Review by rhtaylor — COMMENTED** [review]
text-center removed from header.scss

**Review by RaevLogic — APPROVED** [review]

**Pull request merged**
